import { darculaTheme } from './darcula.theme';


export const blackFoxConsoleTheme = darculaTheme.createFrom({
	themeName: 'Black fox Console',
	variables: {
		'DEPRECATED codeBackGround': '#14171A',
		'DEPRECATED generalBackGround': '#343c45',
		'DEPRECATED generalText': '#a9bacb',
		'DEPRECATED textSelectionBackground': '#3D484A',
		'DEPRECATED border': '#5C6773',
		'DEPRECATED listItem': '#a9bacb',
		'DEPRECATED listItemBackground': '#1d4f73',
		'DEPRECATED listItemSelected': '#F5F7FA',
		'DEPRECATED listItemBackgroundSelected': '#174262',
		'DEPRECATED listItem Background secondary': '#2a3037',
		'DEPRECATED tabBackGround': '#2a3037',
		'DEPRECATED Scrollbar': '#5C6773',
		'DEPRECATED Drag bar': '#000',
		'DEPRECATED Drag bar hoover': '#222',

		'DEPRECATED Folder text': '#8a93ab',
		'DEPRECATED Folder background': '#17171729',

		'DEPRECATED Line numbers': '#5C6773',
		'DEPRECATED Breakpoint': '#db4437',
		'DEPRECATED Cursor': '#ffffff',
		'DEPRECATED Code Punctuation': '#CDD7E0',
		'DEPRECATED Keywords': '#ba4',
		'DEPRECATED Constants': '#BE3F42',
		'DEPRECATED Numbers': '#5F9F5B',
		'DEPRECATED Definitions': '#3689B2',
		'DEPRECATED Top level Variable': '#3689B2',
		'DEPRECATED Local variable': '#CDD7E0',
		'DEPRECATED Object properties': '#3689B2',
		'DEPRECATED Operators': '#A9BACB',
		'DEPRECATED Comments': '#5C6773',
		'DEPRECATED String': '#BC8154',
		'DEPRECATED Regular expressions': '#f50',
		'DEPRECATED Errors in HTML': '#FF2E0B',
		'DEPRECATED CSS selectors': '#555',
		'DEPRECATED HTML tag': '#A673BF',
		'DEPRECATED HTML attribute': '#3689B2',
		'DEPRECATED HTML template': '#00ECFF',
	},
});
