import { darculaTheme } from "./darcula.theme";

export const oneDarkTheme = darculaTheme.createFrom({
    themeName: "One Dark",
    variables: {
        "DEPRECATED codeBackGround": "#31343f",
        "DEPRECATED generalBackGround": "#1e2127",
        "DEPRECATED generalText": "#d8dee9",
        "DEPRECATED textSelectionBackground": "rgba(92,99,112,.5)",
        "DEPRECATED border": "#242627",
        "DEPRECATED listItem": "#bbb",
        "DEPRECATED listItemBackground": "#4b6eaf",
        "DEPRECATED listItemSelected": "#ccc",
        "DEPRECATED listItemBackgroundSelected": "rgba(92,99,112,.25)",
        "DEPRECATED listItem Background secondary": "#49473f",
        "DEPRECATED tabBackGround": "#515658",
        "DEPRECATED Scrollbar": "rgba(134,130,115,.45)",
        "DEPRECATED Drag bar": "#31343f",
        "DEPRECATED Drag bar hoover": "#4d505b",

        "DEPRECATED Folder text": "#8a93ab",
        "DEPRECATED Folder background": "#15151529",

        "DEPRECATED Line numbers": "#494f5a",
        "DEPRECATED Breakpoint": "#bf616a",
        "DEPRECATED Cursor": "#abb2bf",
        "DEPRECATED Code Punctuation": "#bbb",
        "DEPRECATED Keywords": "#81a1c1",
        "DEPRECATED Constants": "#cc7832",
        "DEPRECATED Numbers": "#6897bb",
        "DEPRECATED Definitions": "#f1f1f1",
        "DEPRECATED Top level Variable": "#88c0d0",
        "DEPRECATED Local variable": "#f1f1f1",
        "DEPRECATED Object properties": "#d8dee9",
        "DEPRECATED Operators": "#bbb",
        "DEPRECATED Comments": "#616e88",
        "DEPRECATED String": "#a3be8c",
        "DEPRECATED Regular expressions": "#d08770",
        "DEPRECATED Errors in HTML": "#bf616a",
        "DEPRECATED CSS selectors": "#8fbcbb",
        "DEPRECATED HTML tag": "#ebcb8b",
        "DEPRECATED HTML attribute": "#8fbcbb",
        "DEPRECATED HTML template": "#00ecff",
    },
});
